config/routes.rb
Rails.application.routes.draw do
  root 'data#index'
  resources :data
  get 'data_minbre' => 'data#minbre_csv'
  get 'data_aitomo' => 'data#aitomo_csv'
  post 'scrape' => 'data#scrape_new'
  get 'regi_minbre' => 'data#regi_minbre'
  get 'regi_aitomo' => 'data#regi_aitomo'
  post 'regi_delete' => 'data#delete'
  get 'admin' => 'data#admin'
  post 'admin/edit' => 'data#admin_edit'
  get 'admin/edit/:id' => 'data#admin_edit_breeder'
  post 'admin/edit/:id/change' => 'data#admin_edit_breeder_change'

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  def index
    @data = Datum.last(9)
  end

  def minbre_csv
    bom = "\xFF\xFE".force_encoding("UTF-16LE")
    @min_dogs = OtherDog.where(site_name: 'みんなのブリーダー').select("dog_id", "breeder_id", "dog_type", "birthday", "price", "status")
    send_data bom + @min_dogs.to_csv.encode("UTF-16LE"), filename: "minbre.csv", type: 'text/csv', col_sep: "\2c"
  end

  def aitomo_csv
    bom = "\xFF\xFE".force_encoding("UTF-16LE")
    @ai_dogs = OtherDog.where(site_name: '愛犬の友').select("dog_id", "breeder_id", "dog_type", "birthday", "price", "status")
      send_data bom + @ai_dogs.to_csv.encode("UTF-16LE"), filename: "aitomo.csv", type: 'text/csv'
  end

  def scrape(n)
    agent = Mechanize.new
    page = agent.get("http://breeder-one.jp/search?dog_type=#{n}")
    elements = page.search('.dog') # elements.length => 33
    # 広告以外のものを取得する(9つ目以降は広告じゃない)
    elements_without_ads = elements[8..-1]
    # 「NEW」と付いているものだけselectする
    elements_filter_by_new = elements_without_ads.select { |element|
      element.search("li.new").text == "NEW"
    }
    # ランダムに1つ抽出
    target = elements_filter_by_new.sample

    url = target.at("a").attributes["href"].value

    detail_page = agent.get(url)

    date = detail_page.at('.data tr[7] td').text
    dname = detail_page.at('.data tr[2] a').text
    appeal = detail_page.at('.appeal p').text
    comment = detail_page.at('.table_style7 tr[7] td').text
    bname = detail_page.at('.data tr[9] a').text
    img_url = detail_page.at('#photo_list img')
    img_src = img_url[:src]
    t_date = Datum.create(:date => date, :dog_name => dname, :appeal => appeal, :comment => comment, :url => url, :breeder_name => bname, :img_url => img_src)
  end

  def scrape_new
    dog_types = [1, 2, 9, 4, 8, 3, 18, 59, 60]
    dog_types.each do |dog_type|
      scrape(dog_type)
    end
    redirect_to root_path
  end

  # def regi_minbre
  #   @regi_minbre = OtherDog.where(site_name: 'みんなのブリーダー').order(status: :desc)
  # end

  # def regi_aitomo
  #   @regi_aitomo = OtherDog.where(site_name: '愛犬の友')
  # end

  def admin
      @breeder = Breeder.new
      @breeders = Breeder.all.order(id: :desc)
  end

  def admin_edit
    @breeder = Breeder.new(breeder_params)

    if @breeder.save
      redirect_to '/admin', notice: "登録しました"
    else
      render :admin
    end
  end

  def admin_edit_breeder
    @breeder = Breeder.find(params[:id])
  end

  def admin_edit_breeder_change
    breeder = Breeder.find(params[:id])
    breeder.update_attributes(breeder_id: params[:breeder_id], breeder_name: params[:breeder_name], site_name: params[:site_name])
    redirect_to '/admin'
  end

  def delete
    OtherDog.delete_all
    redirect_to(:back)
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def created
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: 'Datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.fetch(:datum, {})
    end

    def breeder_params
      params.require(:breeder).permit(:breeder_name, :breeder_id, :site_name)
    end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/admin.html.erb
<div class="regi">
  <h1>新規代行登録ブリーダーを登録する</h1>
  <%= form_for @breeder, url: "/admin/edit" do |f| %>
  ブリーダーID : <%= f.text_field :breeder_id %><br>
  ブリーダー名 : <%= f.text_field :breeder_name %><br>
  <%= f.collection_select :site_name, [["みんなのブリーダー", "みんぶり"], ["愛犬の友", "あいとも"]], :first, :last %>
    <%= f.submit %>
  <% end %>

 <% if notice.present? %>
  <%= notice %>
 <% end %>

 <% if @breeder.errors.present? %>
  <%= @breeder.errors.full_messages %>
 <% end %>
</div>

<br>
<br>
<br>
<br>
<div class="table_breeders">
  <table border=1>
    <tr>
      <th>サイト名</th>
      <th>ブリーダーID</th>
      <th>ブリーダー名</th>
      <th></th>
    </tr>
  <% @breeders.each do |breeder| %>
    <tr>
      <th><%= breeder.site_name %></th>
      <th><%= breeder.breeder_id %></th>
      <th><%= breeder.breeder_name %></th>
      <th><a href="/admin/edit/<%= breeder.id %>">編集する</a></th>
    </tr>
    <% end %>
  </table>
</div>

app/views/data/admin_edit_breeder.html.erb
<h1>編集する</h1>

  <%= form_tag("/admin/edit/#{@breeder.id}/change", method: :post) do %>
    <input type="text" name="breeder_id" value="<%= @breeder.breeder_id %>">
    <input type="text" name="breeder_name" value="<%= @breeder.breeder_name %>">
    <select name="site_name">
      <option value="みんなのブリーダー">みんぶり</option>
      <option value="愛犬の友">あいとも</option>
    <input type="submit" value="編集する"></input>


<% end %>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ブリーダーワン！！</h1>

<%= form_tag('/scrape', method: :post) do %>
  <input type="submit" value="スクレイピング"></input>
  <p style="color: red;">※約1分かかります。</p>
<% end %>


<!-- <a href="/regi_minbre">子犬代行登録(みんぶり)へ</a><br>
<a href="/regi_aitomo">子犬代行登録(あいとも)へ</a>
<br> -->

<p>
  Download:
  <%= link_to "みんぶりcsv", "data_minbre" %>
  <%= link_to "あいともcsv", "data_aitomo" %>
</p>

<a href="/admin">管理画面へ</a>

<div class="contents">
  <p>
  <% @data.each do |datum| %>
  【<%= datum.dog_name %>新着子犬】<br>
  <%= datum.appeal %><br>
  <%= datum.comment %>→<a href="http://breeder-one.jp<%= datum.url %>" target="_blank">http://breeder-one.jp<%= datum.url %></a><br>
  今だけ、成約者全員にお祝金10000円プレゼント！<br><br>
  掲載日：<%= datum.date %><br>
  <%= datum.breeder_name %>
  <img src="<%= datum.img_url %>" alt="">
  <hr>
  </p>
<% end %>
</div>

app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/regi_aitomo.html.erb
<%= form_tag('regi_delete', method: :post) do %>
 <input type="submit" value="データを削除する"></input>
<% end %>


<div class="table_aitomo">
  <table border=1>
    <tr>
      <th>id</th>
      <th>breeder_id</th>
      <th>dog_type</th>
      <th>birthday</th>
      <th>price</th>
      <th>status</th>
    </tr>
    <% @regi_aitomo.each do |regi| %>
    <tr>
      <th><%= regi.dog_id %></th>
      <th><%= regi.breeder_id %></th>
      <th><%= regi.dog_type %></th>
      <th><%= regi.birthday %></th>
      <th><%= regi.price %></th>
      <th><%= regi.status %></th>
    </tr>
    <% end %>
  </table>
</div>

app/views/data/regi_minbre.html.erb
<%= form_tag('regi_delete', method: :post) do %>
 <input type="submit" value="データを削除する"></input>
<% end %>


<div class="table_minbre">
  <table border=1>
    <tr>
      <th>id</th>
      <th>breeder_id</th>
      <th>dog_type</th>
      <th>birthday</th>
      <th>price</th>
      <th>status</th>
    </tr>
    <% @regi_minbre.each do |minbre| %>
    <tr>
      <th><%= minbre.dog_id %></th>
      <th><%= minbre.breeder_id %></th>
      <th><%= minbre.dog_type %></th>
      <th><%= minbre.birthday %></th>
      <th><%= minbre.price %></th>
      <th><%= minbre.status %></th>
    </tr>
    <% end %>
  </table>
</div>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>